language: python
python:
    - "3.6" 
branches:
  only:
    - master
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
  - pipenv run python setup.py
script:
  - pipenv run pytest test/*
